version: "3.8"
services:
  wgman:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/db:/app/data/db
    cap_add:
      - NET_ADMIN
    command: bash /app/start.sh
    network_mode: host
    
    # Optional
    # environment:
    #   - PUBLIC_IP=192.168.178.68 
    #   - IP_PREFIX=10.22 #Optional