version: "3"
services:
  wgman:
    build:
      context: .
      dockerfile: app
    volumes:
      - ./data/db:/app/data/db
      - static:/app/src/app/static
    cap_add:
      - NET_ADMIN
    command: bash /app/start.sh
    network_mode: host
    environment:
      - PRODUCTION=true
    #   - PUBLIC_IP=192.168.178.68 
    #   - IP_PREFIX=10.22 #Optional
    restart: unless-stopped
  
  proxy:
    build:
      context: .
      dockerfile: proxy
    ports:
      - 8080:80
    depends_on:
      - wgman
    restart: unless-stopped

volumes:
  static: