version: "3.8"
services:
  wgman:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
      # - ../data/wg:/etc/wireguard
    cap_add:
      - NET_ADMIN
    command: bash /app/.devcontainer/start.sh
    network_mode: host
    environment:
      - PUBLIC_IP=192.168.178.68 #Optional
      # - IP_PREFIX=10.22 #Optional