# Generated by Django 5.0.3 on 2024-03-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('subnet', models.PositiveSmallIntegerField(default=24)),
                ('listen_port', models.PositiveIntegerField(unique=True)),
                ('private_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('private_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('preshared_key', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='wireguard.interface')),
            ],
        ),
    ]
