# Generated by Django 5.0.3 on 2024-03-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0002_remove_interface_ip_address_remove_interface_subnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='subnet_num',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peer',
            name='ip_num',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
