# Generated by Django 5.0.3 on 2024-03-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0003_interface_subnet_num_peer_ip_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('name', 'interface')},
        ),
    ]
