# Generated by Django 5.0.3 on 2024-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0004_alter_peer_name_alter_peer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='dns',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
